[package]
name = "vaulter"
description = "Secure AEAD file encryption utility"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20" }
clio = { version = "0.3.5", features = ["clap", "clap-parse"] }
ring = "0.17.7"
